name: agropine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  google_sign_in: ^6.1.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  geolocator: ^11.0.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0
  provider: ^6.0.0
  connectivity_plus: ^5.0.0
  uuid: ^4.0.0
  image_picker: ^1.0.0
  image: ^4.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/images/logo.png
    - assets/images/landing_image.png
